version: "3.9"
services:
  legolas:
    container_name: legolas
    image: legolas:latest
    working_dir: /go/src/app
    ports:
      - "9999:9999"
    volumes:
      - .:/go/src/app
    depends_on:
      - redis
  redis:
    image: redis
    container_name: legolas-redis
    ports:
      - "6379:6379"
  database:
    image: postgres:latest
    container_name: janus-db
    environment:
      POSTGRES_USER: "legolas"
      POSTGRES_PASSWORD: "legolas"
      POSTGRES_DB: "legolas"
    volumes:
      - legolas-database:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
volumes:
  legolas-database:
