// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/artmisxyz/legolas/ent/predicate"
	"github.com/artmisxyz/legolas/ent/uniswapv3decreaseliqudity"
)

// UniswapV3DecreaseLiqudityDelete is the builder for deleting a UniswapV3DecreaseLiqudity entity.
type UniswapV3DecreaseLiqudityDelete struct {
	config
	hooks    []Hook
	mutation *UniswapV3DecreaseLiqudityMutation
}

// Where appends a list predicates to the UniswapV3DecreaseLiqudityDelete builder.
func (uvld *UniswapV3DecreaseLiqudityDelete) Where(ps ...predicate.UniswapV3DecreaseLiqudity) *UniswapV3DecreaseLiqudityDelete {
	uvld.mutation.Where(ps...)
	return uvld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (uvld *UniswapV3DecreaseLiqudityDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(uvld.hooks) == 0 {
		affected, err = uvld.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UniswapV3DecreaseLiqudityMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			uvld.mutation = mutation
			affected, err = uvld.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(uvld.hooks) - 1; i >= 0; i-- {
			if uvld.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = uvld.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uvld.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (uvld *UniswapV3DecreaseLiqudityDelete) ExecX(ctx context.Context) int {
	n, err := uvld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (uvld *UniswapV3DecreaseLiqudityDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: uniswapv3decreaseliqudity.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: uniswapv3decreaseliqudity.FieldID,
			},
		},
	}
	if ps := uvld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, uvld.driver, _spec)
}

// UniswapV3DecreaseLiqudityDeleteOne is the builder for deleting a single UniswapV3DecreaseLiqudity entity.
type UniswapV3DecreaseLiqudityDeleteOne struct {
	uvld *UniswapV3DecreaseLiqudityDelete
}

// Exec executes the deletion query.
func (uvldo *UniswapV3DecreaseLiqudityDeleteOne) Exec(ctx context.Context) error {
	n, err := uvldo.uvld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{uniswapv3decreaseliqudity.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (uvldo *UniswapV3DecreaseLiqudityDeleteOne) ExecX(ctx context.Context) {
	uvldo.uvld.ExecX(ctx)
}
