// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/artmisxyz/legolas/ent/event"
	"github.com/artmisxyz/legolas/ent/uniswapv3poolmint"
)

// UniswapV3PoolMintCreate is the builder for creating a UniswapV3PoolMint entity.
type UniswapV3PoolMintCreate struct {
	config
	mutation *UniswapV3PoolMintMutation
	hooks    []Hook
}

// SetOwner sets the "owner" field.
func (uvmc *UniswapV3PoolMintCreate) SetOwner(s string) *UniswapV3PoolMintCreate {
	uvmc.mutation.SetOwner(s)
	return uvmc
}

// SetTickLower sets the "tick_lower" field.
func (uvmc *UniswapV3PoolMintCreate) SetTickLower(s string) *UniswapV3PoolMintCreate {
	uvmc.mutation.SetTickLower(s)
	return uvmc
}

// SetTickUpper sets the "tick_upper" field.
func (uvmc *UniswapV3PoolMintCreate) SetTickUpper(s string) *UniswapV3PoolMintCreate {
	uvmc.mutation.SetTickUpper(s)
	return uvmc
}

// SetAmount sets the "amount" field.
func (uvmc *UniswapV3PoolMintCreate) SetAmount(s string) *UniswapV3PoolMintCreate {
	uvmc.mutation.SetAmount(s)
	return uvmc
}

// SetAmount0 sets the "amount0" field.
func (uvmc *UniswapV3PoolMintCreate) SetAmount0(s string) *UniswapV3PoolMintCreate {
	uvmc.mutation.SetAmount0(s)
	return uvmc
}

// SetAmount1 sets the "amount1" field.
func (uvmc *UniswapV3PoolMintCreate) SetAmount1(s string) *UniswapV3PoolMintCreate {
	uvmc.mutation.SetAmount1(s)
	return uvmc
}

// SetEventID sets the "event" edge to the Event entity by ID.
func (uvmc *UniswapV3PoolMintCreate) SetEventID(id int) *UniswapV3PoolMintCreate {
	uvmc.mutation.SetEventID(id)
	return uvmc
}

// SetEvent sets the "event" edge to the Event entity.
func (uvmc *UniswapV3PoolMintCreate) SetEvent(e *Event) *UniswapV3PoolMintCreate {
	return uvmc.SetEventID(e.ID)
}

// Mutation returns the UniswapV3PoolMintMutation object of the builder.
func (uvmc *UniswapV3PoolMintCreate) Mutation() *UniswapV3PoolMintMutation {
	return uvmc.mutation
}

// Save creates the UniswapV3PoolMint in the database.
func (uvmc *UniswapV3PoolMintCreate) Save(ctx context.Context) (*UniswapV3PoolMint, error) {
	var (
		err  error
		node *UniswapV3PoolMint
	)
	if len(uvmc.hooks) == 0 {
		if err = uvmc.check(); err != nil {
			return nil, err
		}
		node, err = uvmc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UniswapV3PoolMintMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = uvmc.check(); err != nil {
				return nil, err
			}
			uvmc.mutation = mutation
			if node, err = uvmc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(uvmc.hooks) - 1; i >= 0; i-- {
			if uvmc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = uvmc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uvmc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (uvmc *UniswapV3PoolMintCreate) SaveX(ctx context.Context) *UniswapV3PoolMint {
	v, err := uvmc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uvmc *UniswapV3PoolMintCreate) Exec(ctx context.Context) error {
	_, err := uvmc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uvmc *UniswapV3PoolMintCreate) ExecX(ctx context.Context) {
	if err := uvmc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uvmc *UniswapV3PoolMintCreate) check() error {
	if _, ok := uvmc.mutation.Owner(); !ok {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required field "owner"`)}
	}
	if _, ok := uvmc.mutation.TickLower(); !ok {
		return &ValidationError{Name: "tick_lower", err: errors.New(`ent: missing required field "tick_lower"`)}
	}
	if _, ok := uvmc.mutation.TickUpper(); !ok {
		return &ValidationError{Name: "tick_upper", err: errors.New(`ent: missing required field "tick_upper"`)}
	}
	if _, ok := uvmc.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "amount"`)}
	}
	if _, ok := uvmc.mutation.Amount0(); !ok {
		return &ValidationError{Name: "amount0", err: errors.New(`ent: missing required field "amount0"`)}
	}
	if _, ok := uvmc.mutation.Amount1(); !ok {
		return &ValidationError{Name: "amount1", err: errors.New(`ent: missing required field "amount1"`)}
	}
	if _, ok := uvmc.mutation.EventID(); !ok {
		return &ValidationError{Name: "event", err: errors.New("ent: missing required edge \"event\"")}
	}
	return nil
}

func (uvmc *UniswapV3PoolMintCreate) sqlSave(ctx context.Context) (*UniswapV3PoolMint, error) {
	_node, _spec := uvmc.createSpec()
	if err := sqlgraph.CreateNode(ctx, uvmc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (uvmc *UniswapV3PoolMintCreate) createSpec() (*UniswapV3PoolMint, *sqlgraph.CreateSpec) {
	var (
		_node = &UniswapV3PoolMint{config: uvmc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: uniswapv3poolmint.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: uniswapv3poolmint.FieldID,
			},
		}
	)
	if value, ok := uvmc.mutation.Owner(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: uniswapv3poolmint.FieldOwner,
		})
		_node.Owner = value
	}
	if value, ok := uvmc.mutation.TickLower(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: uniswapv3poolmint.FieldTickLower,
		})
		_node.TickLower = value
	}
	if value, ok := uvmc.mutation.TickUpper(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: uniswapv3poolmint.FieldTickUpper,
		})
		_node.TickUpper = value
	}
	if value, ok := uvmc.mutation.Amount(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: uniswapv3poolmint.FieldAmount,
		})
		_node.Amount = value
	}
	if value, ok := uvmc.mutation.Amount0(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: uniswapv3poolmint.FieldAmount0,
		})
		_node.Amount0 = value
	}
	if value, ok := uvmc.mutation.Amount1(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: uniswapv3poolmint.FieldAmount1,
		})
		_node.Amount1 = value
	}
	if nodes := uvmc.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   uniswapv3poolmint.EventTable,
			Columns: []string{uniswapv3poolmint.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: event.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.event_id = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UniswapV3PoolMintCreateBulk is the builder for creating many UniswapV3PoolMint entities in bulk.
type UniswapV3PoolMintCreateBulk struct {
	config
	builders []*UniswapV3PoolMintCreate
}

// Save creates the UniswapV3PoolMint entities in the database.
func (uvmcb *UniswapV3PoolMintCreateBulk) Save(ctx context.Context) ([]*UniswapV3PoolMint, error) {
	specs := make([]*sqlgraph.CreateSpec, len(uvmcb.builders))
	nodes := make([]*UniswapV3PoolMint, len(uvmcb.builders))
	mutators := make([]Mutator, len(uvmcb.builders))
	for i := range uvmcb.builders {
		func(i int, root context.Context) {
			builder := uvmcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UniswapV3PoolMintMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, uvmcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, uvmcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, uvmcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (uvmcb *UniswapV3PoolMintCreateBulk) SaveX(ctx context.Context) []*UniswapV3PoolMint {
	v, err := uvmcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uvmcb *UniswapV3PoolMintCreateBulk) Exec(ctx context.Context) error {
	_, err := uvmcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uvmcb *UniswapV3PoolMintCreateBulk) ExecX(ctx context.Context) {
	if err := uvmcb.Exec(ctx); err != nil {
		panic(err)
	}
}
