// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/artmisxyz/legolas/ent/event"
	"github.com/artmisxyz/legolas/ent/predicate"
	"github.com/artmisxyz/legolas/ent/uniswapv3transfer"
)

// UniswapV3TransferQuery is the builder for querying UniswapV3Transfer entities.
type UniswapV3TransferQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.UniswapV3Transfer
	// eager-loading edges.
	withEvent *EventQuery
	withFKs   bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UniswapV3TransferQuery builder.
func (uvq *UniswapV3TransferQuery) Where(ps ...predicate.UniswapV3Transfer) *UniswapV3TransferQuery {
	uvq.predicates = append(uvq.predicates, ps...)
	return uvq
}

// Limit adds a limit step to the query.
func (uvq *UniswapV3TransferQuery) Limit(limit int) *UniswapV3TransferQuery {
	uvq.limit = &limit
	return uvq
}

// Offset adds an offset step to the query.
func (uvq *UniswapV3TransferQuery) Offset(offset int) *UniswapV3TransferQuery {
	uvq.offset = &offset
	return uvq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (uvq *UniswapV3TransferQuery) Unique(unique bool) *UniswapV3TransferQuery {
	uvq.unique = &unique
	return uvq
}

// Order adds an order step to the query.
func (uvq *UniswapV3TransferQuery) Order(o ...OrderFunc) *UniswapV3TransferQuery {
	uvq.order = append(uvq.order, o...)
	return uvq
}

// QueryEvent chains the current query on the "event" edge.
func (uvq *UniswapV3TransferQuery) QueryEvent() *EventQuery {
	query := &EventQuery{config: uvq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := uvq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := uvq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(uniswapv3transfer.Table, uniswapv3transfer.FieldID, selector),
			sqlgraph.To(event.Table, event.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, uniswapv3transfer.EventTable, uniswapv3transfer.EventColumn),
		)
		fromU = sqlgraph.SetNeighbors(uvq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UniswapV3Transfer entity from the query.
// Returns a *NotFoundError when no UniswapV3Transfer was found.
func (uvq *UniswapV3TransferQuery) First(ctx context.Context) (*UniswapV3Transfer, error) {
	nodes, err := uvq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{uniswapv3transfer.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (uvq *UniswapV3TransferQuery) FirstX(ctx context.Context) *UniswapV3Transfer {
	node, err := uvq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UniswapV3Transfer ID from the query.
// Returns a *NotFoundError when no UniswapV3Transfer ID was found.
func (uvq *UniswapV3TransferQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uvq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{uniswapv3transfer.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (uvq *UniswapV3TransferQuery) FirstIDX(ctx context.Context) int {
	id, err := uvq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UniswapV3Transfer entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one UniswapV3Transfer entity is not found.
// Returns a *NotFoundError when no UniswapV3Transfer entities are found.
func (uvq *UniswapV3TransferQuery) Only(ctx context.Context) (*UniswapV3Transfer, error) {
	nodes, err := uvq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{uniswapv3transfer.Label}
	default:
		return nil, &NotSingularError{uniswapv3transfer.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (uvq *UniswapV3TransferQuery) OnlyX(ctx context.Context) *UniswapV3Transfer {
	node, err := uvq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UniswapV3Transfer ID in the query.
// Returns a *NotSingularError when exactly one UniswapV3Transfer ID is not found.
// Returns a *NotFoundError when no entities are found.
func (uvq *UniswapV3TransferQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uvq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{uniswapv3transfer.Label}
	default:
		err = &NotSingularError{uniswapv3transfer.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (uvq *UniswapV3TransferQuery) OnlyIDX(ctx context.Context) int {
	id, err := uvq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UniswapV3Transfers.
func (uvq *UniswapV3TransferQuery) All(ctx context.Context) ([]*UniswapV3Transfer, error) {
	if err := uvq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return uvq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (uvq *UniswapV3TransferQuery) AllX(ctx context.Context) []*UniswapV3Transfer {
	nodes, err := uvq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UniswapV3Transfer IDs.
func (uvq *UniswapV3TransferQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := uvq.Select(uniswapv3transfer.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (uvq *UniswapV3TransferQuery) IDsX(ctx context.Context) []int {
	ids, err := uvq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (uvq *UniswapV3TransferQuery) Count(ctx context.Context) (int, error) {
	if err := uvq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return uvq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (uvq *UniswapV3TransferQuery) CountX(ctx context.Context) int {
	count, err := uvq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (uvq *UniswapV3TransferQuery) Exist(ctx context.Context) (bool, error) {
	if err := uvq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return uvq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (uvq *UniswapV3TransferQuery) ExistX(ctx context.Context) bool {
	exist, err := uvq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UniswapV3TransferQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (uvq *UniswapV3TransferQuery) Clone() *UniswapV3TransferQuery {
	if uvq == nil {
		return nil
	}
	return &UniswapV3TransferQuery{
		config:     uvq.config,
		limit:      uvq.limit,
		offset:     uvq.offset,
		order:      append([]OrderFunc{}, uvq.order...),
		predicates: append([]predicate.UniswapV3Transfer{}, uvq.predicates...),
		withEvent:  uvq.withEvent.Clone(),
		// clone intermediate query.
		sql:  uvq.sql.Clone(),
		path: uvq.path,
	}
}

// WithEvent tells the query-builder to eager-load the nodes that are connected to
// the "event" edge. The optional arguments are used to configure the query builder of the edge.
func (uvq *UniswapV3TransferQuery) WithEvent(opts ...func(*EventQuery)) *UniswapV3TransferQuery {
	query := &EventQuery{config: uvq.config}
	for _, opt := range opts {
		opt(query)
	}
	uvq.withEvent = query
	return uvq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TokenID string `json:"token_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UniswapV3Transfer.Query().
//		GroupBy(uniswapv3transfer.FieldTokenID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (uvq *UniswapV3TransferQuery) GroupBy(field string, fields ...string) *UniswapV3TransferGroupBy {
	group := &UniswapV3TransferGroupBy{config: uvq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := uvq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return uvq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TokenID string `json:"token_id,omitempty"`
//	}
//
//	client.UniswapV3Transfer.Query().
//		Select(uniswapv3transfer.FieldTokenID).
//		Scan(ctx, &v)
//
func (uvq *UniswapV3TransferQuery) Select(fields ...string) *UniswapV3TransferSelect {
	uvq.fields = append(uvq.fields, fields...)
	return &UniswapV3TransferSelect{UniswapV3TransferQuery: uvq}
}

func (uvq *UniswapV3TransferQuery) prepareQuery(ctx context.Context) error {
	for _, f := range uvq.fields {
		if !uniswapv3transfer.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if uvq.path != nil {
		prev, err := uvq.path(ctx)
		if err != nil {
			return err
		}
		uvq.sql = prev
	}
	return nil
}

func (uvq *UniswapV3TransferQuery) sqlAll(ctx context.Context) ([]*UniswapV3Transfer, error) {
	var (
		nodes       = []*UniswapV3Transfer{}
		withFKs     = uvq.withFKs
		_spec       = uvq.querySpec()
		loadedTypes = [1]bool{
			uvq.withEvent != nil,
		}
	)
	if uvq.withEvent != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, uniswapv3transfer.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &UniswapV3Transfer{config: uvq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, uvq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := uvq.withEvent; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*UniswapV3Transfer)
		for i := range nodes {
			if nodes[i].event_id == nil {
				continue
			}
			fk := *nodes[i].event_id
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(event.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "event_id" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Event = n
			}
		}
	}

	return nodes, nil
}

func (uvq *UniswapV3TransferQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := uvq.querySpec()
	return sqlgraph.CountNodes(ctx, uvq.driver, _spec)
}

func (uvq *UniswapV3TransferQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := uvq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (uvq *UniswapV3TransferQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   uniswapv3transfer.Table,
			Columns: uniswapv3transfer.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: uniswapv3transfer.FieldID,
			},
		},
		From:   uvq.sql,
		Unique: true,
	}
	if unique := uvq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := uvq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, uniswapv3transfer.FieldID)
		for i := range fields {
			if fields[i] != uniswapv3transfer.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := uvq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := uvq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := uvq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := uvq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (uvq *UniswapV3TransferQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(uvq.driver.Dialect())
	t1 := builder.Table(uniswapv3transfer.Table)
	columns := uvq.fields
	if len(columns) == 0 {
		columns = uniswapv3transfer.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if uvq.sql != nil {
		selector = uvq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range uvq.predicates {
		p(selector)
	}
	for _, p := range uvq.order {
		p(selector)
	}
	if offset := uvq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := uvq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UniswapV3TransferGroupBy is the group-by builder for UniswapV3Transfer entities.
type UniswapV3TransferGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (uvgb *UniswapV3TransferGroupBy) Aggregate(fns ...AggregateFunc) *UniswapV3TransferGroupBy {
	uvgb.fns = append(uvgb.fns, fns...)
	return uvgb
}

// Scan applies the group-by query and scans the result into the given value.
func (uvgb *UniswapV3TransferGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := uvgb.path(ctx)
	if err != nil {
		return err
	}
	uvgb.sql = query
	return uvgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (uvgb *UniswapV3TransferGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := uvgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (uvgb *UniswapV3TransferGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(uvgb.fields) > 1 {
		return nil, errors.New("ent: UniswapV3TransferGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := uvgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (uvgb *UniswapV3TransferGroupBy) StringsX(ctx context.Context) []string {
	v, err := uvgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (uvgb *UniswapV3TransferGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = uvgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{uniswapv3transfer.Label}
	default:
		err = fmt.Errorf("ent: UniswapV3TransferGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (uvgb *UniswapV3TransferGroupBy) StringX(ctx context.Context) string {
	v, err := uvgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (uvgb *UniswapV3TransferGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(uvgb.fields) > 1 {
		return nil, errors.New("ent: UniswapV3TransferGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := uvgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (uvgb *UniswapV3TransferGroupBy) IntsX(ctx context.Context) []int {
	v, err := uvgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (uvgb *UniswapV3TransferGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = uvgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{uniswapv3transfer.Label}
	default:
		err = fmt.Errorf("ent: UniswapV3TransferGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (uvgb *UniswapV3TransferGroupBy) IntX(ctx context.Context) int {
	v, err := uvgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (uvgb *UniswapV3TransferGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(uvgb.fields) > 1 {
		return nil, errors.New("ent: UniswapV3TransferGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := uvgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (uvgb *UniswapV3TransferGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := uvgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (uvgb *UniswapV3TransferGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = uvgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{uniswapv3transfer.Label}
	default:
		err = fmt.Errorf("ent: UniswapV3TransferGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (uvgb *UniswapV3TransferGroupBy) Float64X(ctx context.Context) float64 {
	v, err := uvgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (uvgb *UniswapV3TransferGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(uvgb.fields) > 1 {
		return nil, errors.New("ent: UniswapV3TransferGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := uvgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (uvgb *UniswapV3TransferGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := uvgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (uvgb *UniswapV3TransferGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = uvgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{uniswapv3transfer.Label}
	default:
		err = fmt.Errorf("ent: UniswapV3TransferGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (uvgb *UniswapV3TransferGroupBy) BoolX(ctx context.Context) bool {
	v, err := uvgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (uvgb *UniswapV3TransferGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range uvgb.fields {
		if !uniswapv3transfer.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := uvgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uvgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (uvgb *UniswapV3TransferGroupBy) sqlQuery() *sql.Selector {
	selector := uvgb.sql.Select()
	aggregation := make([]string, 0, len(uvgb.fns))
	for _, fn := range uvgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(uvgb.fields)+len(uvgb.fns))
		for _, f := range uvgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(uvgb.fields...)...)
}

// UniswapV3TransferSelect is the builder for selecting fields of UniswapV3Transfer entities.
type UniswapV3TransferSelect struct {
	*UniswapV3TransferQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (uvs *UniswapV3TransferSelect) Scan(ctx context.Context, v interface{}) error {
	if err := uvs.prepareQuery(ctx); err != nil {
		return err
	}
	uvs.sql = uvs.UniswapV3TransferQuery.sqlQuery(ctx)
	return uvs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (uvs *UniswapV3TransferSelect) ScanX(ctx context.Context, v interface{}) {
	if err := uvs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (uvs *UniswapV3TransferSelect) Strings(ctx context.Context) ([]string, error) {
	if len(uvs.fields) > 1 {
		return nil, errors.New("ent: UniswapV3TransferSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := uvs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (uvs *UniswapV3TransferSelect) StringsX(ctx context.Context) []string {
	v, err := uvs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (uvs *UniswapV3TransferSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = uvs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{uniswapv3transfer.Label}
	default:
		err = fmt.Errorf("ent: UniswapV3TransferSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (uvs *UniswapV3TransferSelect) StringX(ctx context.Context) string {
	v, err := uvs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (uvs *UniswapV3TransferSelect) Ints(ctx context.Context) ([]int, error) {
	if len(uvs.fields) > 1 {
		return nil, errors.New("ent: UniswapV3TransferSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := uvs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (uvs *UniswapV3TransferSelect) IntsX(ctx context.Context) []int {
	v, err := uvs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (uvs *UniswapV3TransferSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = uvs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{uniswapv3transfer.Label}
	default:
		err = fmt.Errorf("ent: UniswapV3TransferSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (uvs *UniswapV3TransferSelect) IntX(ctx context.Context) int {
	v, err := uvs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (uvs *UniswapV3TransferSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(uvs.fields) > 1 {
		return nil, errors.New("ent: UniswapV3TransferSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := uvs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (uvs *UniswapV3TransferSelect) Float64sX(ctx context.Context) []float64 {
	v, err := uvs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (uvs *UniswapV3TransferSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = uvs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{uniswapv3transfer.Label}
	default:
		err = fmt.Errorf("ent: UniswapV3TransferSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (uvs *UniswapV3TransferSelect) Float64X(ctx context.Context) float64 {
	v, err := uvs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (uvs *UniswapV3TransferSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(uvs.fields) > 1 {
		return nil, errors.New("ent: UniswapV3TransferSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := uvs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (uvs *UniswapV3TransferSelect) BoolsX(ctx context.Context) []bool {
	v, err := uvs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (uvs *UniswapV3TransferSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = uvs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{uniswapv3transfer.Label}
	default:
		err = fmt.Errorf("ent: UniswapV3TransferSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (uvs *UniswapV3TransferSelect) BoolX(ctx context.Context) bool {
	v, err := uvs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (uvs *UniswapV3TransferSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := uvs.sql.Query()
	if err := uvs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
