// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/artmisxyz/legolas/ent/predicate"
	"github.com/artmisxyz/legolas/ent/uniswapv3collect"
)

// UniswapV3CollectDelete is the builder for deleting a UniswapV3Collect entity.
type UniswapV3CollectDelete struct {
	config
	hooks    []Hook
	mutation *UniswapV3CollectMutation
}

// Where appends a list predicates to the UniswapV3CollectDelete builder.
func (uvd *UniswapV3CollectDelete) Where(ps ...predicate.UniswapV3Collect) *UniswapV3CollectDelete {
	uvd.mutation.Where(ps...)
	return uvd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (uvd *UniswapV3CollectDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(uvd.hooks) == 0 {
		affected, err = uvd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UniswapV3CollectMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			uvd.mutation = mutation
			affected, err = uvd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(uvd.hooks) - 1; i >= 0; i-- {
			if uvd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = uvd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uvd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (uvd *UniswapV3CollectDelete) ExecX(ctx context.Context) int {
	n, err := uvd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (uvd *UniswapV3CollectDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: uniswapv3collect.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: uniswapv3collect.FieldID,
			},
		},
	}
	if ps := uvd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, uvd.driver, _spec)
}

// UniswapV3CollectDeleteOne is the builder for deleting a single UniswapV3Collect entity.
type UniswapV3CollectDeleteOne struct {
	uvd *UniswapV3CollectDelete
}

// Exec executes the deletion query.
func (uvdo *UniswapV3CollectDeleteOne) Exec(ctx context.Context) error {
	n, err := uvdo.uvd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{uniswapv3collect.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (uvdo *UniswapV3CollectDeleteOne) ExecX(ctx context.Context) {
	uvdo.uvd.ExecX(ctx)
}
