// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/artmisxyz/legolas/ent/event"
	"github.com/artmisxyz/legolas/ent/predicate"
	"github.com/artmisxyz/legolas/ent/uniswapv3poolswap"
)

// UniswapV3PoolSwapQuery is the builder for querying UniswapV3PoolSwap entities.
type UniswapV3PoolSwapQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.UniswapV3PoolSwap
	// eager-loading edges.
	withEvent *EventQuery
	withFKs   bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UniswapV3PoolSwapQuery builder.
func (uvsq *UniswapV3PoolSwapQuery) Where(ps ...predicate.UniswapV3PoolSwap) *UniswapV3PoolSwapQuery {
	uvsq.predicates = append(uvsq.predicates, ps...)
	return uvsq
}

// Limit adds a limit step to the query.
func (uvsq *UniswapV3PoolSwapQuery) Limit(limit int) *UniswapV3PoolSwapQuery {
	uvsq.limit = &limit
	return uvsq
}

// Offset adds an offset step to the query.
func (uvsq *UniswapV3PoolSwapQuery) Offset(offset int) *UniswapV3PoolSwapQuery {
	uvsq.offset = &offset
	return uvsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (uvsq *UniswapV3PoolSwapQuery) Unique(unique bool) *UniswapV3PoolSwapQuery {
	uvsq.unique = &unique
	return uvsq
}

// Order adds an order step to the query.
func (uvsq *UniswapV3PoolSwapQuery) Order(o ...OrderFunc) *UniswapV3PoolSwapQuery {
	uvsq.order = append(uvsq.order, o...)
	return uvsq
}

// QueryEvent chains the current query on the "event" edge.
func (uvsq *UniswapV3PoolSwapQuery) QueryEvent() *EventQuery {
	query := &EventQuery{config: uvsq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := uvsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := uvsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(uniswapv3poolswap.Table, uniswapv3poolswap.FieldID, selector),
			sqlgraph.To(event.Table, event.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, uniswapv3poolswap.EventTable, uniswapv3poolswap.EventColumn),
		)
		fromU = sqlgraph.SetNeighbors(uvsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UniswapV3PoolSwap entity from the query.
// Returns a *NotFoundError when no UniswapV3PoolSwap was found.
func (uvsq *UniswapV3PoolSwapQuery) First(ctx context.Context) (*UniswapV3PoolSwap, error) {
	nodes, err := uvsq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{uniswapv3poolswap.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (uvsq *UniswapV3PoolSwapQuery) FirstX(ctx context.Context) *UniswapV3PoolSwap {
	node, err := uvsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UniswapV3PoolSwap ID from the query.
// Returns a *NotFoundError when no UniswapV3PoolSwap ID was found.
func (uvsq *UniswapV3PoolSwapQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uvsq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{uniswapv3poolswap.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (uvsq *UniswapV3PoolSwapQuery) FirstIDX(ctx context.Context) int {
	id, err := uvsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UniswapV3PoolSwap entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one UniswapV3PoolSwap entity is not found.
// Returns a *NotFoundError when no UniswapV3PoolSwap entities are found.
func (uvsq *UniswapV3PoolSwapQuery) Only(ctx context.Context) (*UniswapV3PoolSwap, error) {
	nodes, err := uvsq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{uniswapv3poolswap.Label}
	default:
		return nil, &NotSingularError{uniswapv3poolswap.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (uvsq *UniswapV3PoolSwapQuery) OnlyX(ctx context.Context) *UniswapV3PoolSwap {
	node, err := uvsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UniswapV3PoolSwap ID in the query.
// Returns a *NotSingularError when exactly one UniswapV3PoolSwap ID is not found.
// Returns a *NotFoundError when no entities are found.
func (uvsq *UniswapV3PoolSwapQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uvsq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{uniswapv3poolswap.Label}
	default:
		err = &NotSingularError{uniswapv3poolswap.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (uvsq *UniswapV3PoolSwapQuery) OnlyIDX(ctx context.Context) int {
	id, err := uvsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UniswapV3PoolSwaps.
func (uvsq *UniswapV3PoolSwapQuery) All(ctx context.Context) ([]*UniswapV3PoolSwap, error) {
	if err := uvsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return uvsq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (uvsq *UniswapV3PoolSwapQuery) AllX(ctx context.Context) []*UniswapV3PoolSwap {
	nodes, err := uvsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UniswapV3PoolSwap IDs.
func (uvsq *UniswapV3PoolSwapQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := uvsq.Select(uniswapv3poolswap.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (uvsq *UniswapV3PoolSwapQuery) IDsX(ctx context.Context) []int {
	ids, err := uvsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (uvsq *UniswapV3PoolSwapQuery) Count(ctx context.Context) (int, error) {
	if err := uvsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return uvsq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (uvsq *UniswapV3PoolSwapQuery) CountX(ctx context.Context) int {
	count, err := uvsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (uvsq *UniswapV3PoolSwapQuery) Exist(ctx context.Context) (bool, error) {
	if err := uvsq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return uvsq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (uvsq *UniswapV3PoolSwapQuery) ExistX(ctx context.Context) bool {
	exist, err := uvsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UniswapV3PoolSwapQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (uvsq *UniswapV3PoolSwapQuery) Clone() *UniswapV3PoolSwapQuery {
	if uvsq == nil {
		return nil
	}
	return &UniswapV3PoolSwapQuery{
		config:     uvsq.config,
		limit:      uvsq.limit,
		offset:     uvsq.offset,
		order:      append([]OrderFunc{}, uvsq.order...),
		predicates: append([]predicate.UniswapV3PoolSwap{}, uvsq.predicates...),
		withEvent:  uvsq.withEvent.Clone(),
		// clone intermediate query.
		sql:  uvsq.sql.Clone(),
		path: uvsq.path,
	}
}

// WithEvent tells the query-builder to eager-load the nodes that are connected to
// the "event" edge. The optional arguments are used to configure the query builder of the edge.
func (uvsq *UniswapV3PoolSwapQuery) WithEvent(opts ...func(*EventQuery)) *UniswapV3PoolSwapQuery {
	query := &EventQuery{config: uvsq.config}
	for _, opt := range opts {
		opt(query)
	}
	uvsq.withEvent = query
	return uvsq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Sender string `json:"sender,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UniswapV3PoolSwap.Query().
//		GroupBy(uniswapv3poolswap.FieldSender).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (uvsq *UniswapV3PoolSwapQuery) GroupBy(field string, fields ...string) *UniswapV3PoolSwapGroupBy {
	group := &UniswapV3PoolSwapGroupBy{config: uvsq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := uvsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return uvsq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Sender string `json:"sender,omitempty"`
//	}
//
//	client.UniswapV3PoolSwap.Query().
//		Select(uniswapv3poolswap.FieldSender).
//		Scan(ctx, &v)
//
func (uvsq *UniswapV3PoolSwapQuery) Select(fields ...string) *UniswapV3PoolSwapSelect {
	uvsq.fields = append(uvsq.fields, fields...)
	return &UniswapV3PoolSwapSelect{UniswapV3PoolSwapQuery: uvsq}
}

func (uvsq *UniswapV3PoolSwapQuery) prepareQuery(ctx context.Context) error {
	for _, f := range uvsq.fields {
		if !uniswapv3poolswap.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if uvsq.path != nil {
		prev, err := uvsq.path(ctx)
		if err != nil {
			return err
		}
		uvsq.sql = prev
	}
	return nil
}

func (uvsq *UniswapV3PoolSwapQuery) sqlAll(ctx context.Context) ([]*UniswapV3PoolSwap, error) {
	var (
		nodes       = []*UniswapV3PoolSwap{}
		withFKs     = uvsq.withFKs
		_spec       = uvsq.querySpec()
		loadedTypes = [1]bool{
			uvsq.withEvent != nil,
		}
	)
	if uvsq.withEvent != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, uniswapv3poolswap.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &UniswapV3PoolSwap{config: uvsq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, uvsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := uvsq.withEvent; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*UniswapV3PoolSwap)
		for i := range nodes {
			if nodes[i].event_id == nil {
				continue
			}
			fk := *nodes[i].event_id
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(event.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "event_id" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Event = n
			}
		}
	}

	return nodes, nil
}

func (uvsq *UniswapV3PoolSwapQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := uvsq.querySpec()
	return sqlgraph.CountNodes(ctx, uvsq.driver, _spec)
}

func (uvsq *UniswapV3PoolSwapQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := uvsq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (uvsq *UniswapV3PoolSwapQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   uniswapv3poolswap.Table,
			Columns: uniswapv3poolswap.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: uniswapv3poolswap.FieldID,
			},
		},
		From:   uvsq.sql,
		Unique: true,
	}
	if unique := uvsq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := uvsq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, uniswapv3poolswap.FieldID)
		for i := range fields {
			if fields[i] != uniswapv3poolswap.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := uvsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := uvsq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := uvsq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := uvsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (uvsq *UniswapV3PoolSwapQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(uvsq.driver.Dialect())
	t1 := builder.Table(uniswapv3poolswap.Table)
	columns := uvsq.fields
	if len(columns) == 0 {
		columns = uniswapv3poolswap.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if uvsq.sql != nil {
		selector = uvsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range uvsq.predicates {
		p(selector)
	}
	for _, p := range uvsq.order {
		p(selector)
	}
	if offset := uvsq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := uvsq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UniswapV3PoolSwapGroupBy is the group-by builder for UniswapV3PoolSwap entities.
type UniswapV3PoolSwapGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (uvsgb *UniswapV3PoolSwapGroupBy) Aggregate(fns ...AggregateFunc) *UniswapV3PoolSwapGroupBy {
	uvsgb.fns = append(uvsgb.fns, fns...)
	return uvsgb
}

// Scan applies the group-by query and scans the result into the given value.
func (uvsgb *UniswapV3PoolSwapGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := uvsgb.path(ctx)
	if err != nil {
		return err
	}
	uvsgb.sql = query
	return uvsgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (uvsgb *UniswapV3PoolSwapGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := uvsgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (uvsgb *UniswapV3PoolSwapGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(uvsgb.fields) > 1 {
		return nil, errors.New("ent: UniswapV3PoolSwapGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := uvsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (uvsgb *UniswapV3PoolSwapGroupBy) StringsX(ctx context.Context) []string {
	v, err := uvsgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (uvsgb *UniswapV3PoolSwapGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = uvsgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{uniswapv3poolswap.Label}
	default:
		err = fmt.Errorf("ent: UniswapV3PoolSwapGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (uvsgb *UniswapV3PoolSwapGroupBy) StringX(ctx context.Context) string {
	v, err := uvsgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (uvsgb *UniswapV3PoolSwapGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(uvsgb.fields) > 1 {
		return nil, errors.New("ent: UniswapV3PoolSwapGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := uvsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (uvsgb *UniswapV3PoolSwapGroupBy) IntsX(ctx context.Context) []int {
	v, err := uvsgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (uvsgb *UniswapV3PoolSwapGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = uvsgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{uniswapv3poolswap.Label}
	default:
		err = fmt.Errorf("ent: UniswapV3PoolSwapGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (uvsgb *UniswapV3PoolSwapGroupBy) IntX(ctx context.Context) int {
	v, err := uvsgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (uvsgb *UniswapV3PoolSwapGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(uvsgb.fields) > 1 {
		return nil, errors.New("ent: UniswapV3PoolSwapGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := uvsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (uvsgb *UniswapV3PoolSwapGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := uvsgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (uvsgb *UniswapV3PoolSwapGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = uvsgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{uniswapv3poolswap.Label}
	default:
		err = fmt.Errorf("ent: UniswapV3PoolSwapGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (uvsgb *UniswapV3PoolSwapGroupBy) Float64X(ctx context.Context) float64 {
	v, err := uvsgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (uvsgb *UniswapV3PoolSwapGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(uvsgb.fields) > 1 {
		return nil, errors.New("ent: UniswapV3PoolSwapGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := uvsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (uvsgb *UniswapV3PoolSwapGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := uvsgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (uvsgb *UniswapV3PoolSwapGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = uvsgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{uniswapv3poolswap.Label}
	default:
		err = fmt.Errorf("ent: UniswapV3PoolSwapGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (uvsgb *UniswapV3PoolSwapGroupBy) BoolX(ctx context.Context) bool {
	v, err := uvsgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (uvsgb *UniswapV3PoolSwapGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range uvsgb.fields {
		if !uniswapv3poolswap.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := uvsgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uvsgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (uvsgb *UniswapV3PoolSwapGroupBy) sqlQuery() *sql.Selector {
	selector := uvsgb.sql.Select()
	aggregation := make([]string, 0, len(uvsgb.fns))
	for _, fn := range uvsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(uvsgb.fields)+len(uvsgb.fns))
		for _, f := range uvsgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(uvsgb.fields...)...)
}

// UniswapV3PoolSwapSelect is the builder for selecting fields of UniswapV3PoolSwap entities.
type UniswapV3PoolSwapSelect struct {
	*UniswapV3PoolSwapQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (uvss *UniswapV3PoolSwapSelect) Scan(ctx context.Context, v interface{}) error {
	if err := uvss.prepareQuery(ctx); err != nil {
		return err
	}
	uvss.sql = uvss.UniswapV3PoolSwapQuery.sqlQuery(ctx)
	return uvss.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (uvss *UniswapV3PoolSwapSelect) ScanX(ctx context.Context, v interface{}) {
	if err := uvss.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (uvss *UniswapV3PoolSwapSelect) Strings(ctx context.Context) ([]string, error) {
	if len(uvss.fields) > 1 {
		return nil, errors.New("ent: UniswapV3PoolSwapSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := uvss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (uvss *UniswapV3PoolSwapSelect) StringsX(ctx context.Context) []string {
	v, err := uvss.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (uvss *UniswapV3PoolSwapSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = uvss.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{uniswapv3poolswap.Label}
	default:
		err = fmt.Errorf("ent: UniswapV3PoolSwapSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (uvss *UniswapV3PoolSwapSelect) StringX(ctx context.Context) string {
	v, err := uvss.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (uvss *UniswapV3PoolSwapSelect) Ints(ctx context.Context) ([]int, error) {
	if len(uvss.fields) > 1 {
		return nil, errors.New("ent: UniswapV3PoolSwapSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := uvss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (uvss *UniswapV3PoolSwapSelect) IntsX(ctx context.Context) []int {
	v, err := uvss.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (uvss *UniswapV3PoolSwapSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = uvss.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{uniswapv3poolswap.Label}
	default:
		err = fmt.Errorf("ent: UniswapV3PoolSwapSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (uvss *UniswapV3PoolSwapSelect) IntX(ctx context.Context) int {
	v, err := uvss.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (uvss *UniswapV3PoolSwapSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(uvss.fields) > 1 {
		return nil, errors.New("ent: UniswapV3PoolSwapSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := uvss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (uvss *UniswapV3PoolSwapSelect) Float64sX(ctx context.Context) []float64 {
	v, err := uvss.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (uvss *UniswapV3PoolSwapSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = uvss.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{uniswapv3poolswap.Label}
	default:
		err = fmt.Errorf("ent: UniswapV3PoolSwapSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (uvss *UniswapV3PoolSwapSelect) Float64X(ctx context.Context) float64 {
	v, err := uvss.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (uvss *UniswapV3PoolSwapSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(uvss.fields) > 1 {
		return nil, errors.New("ent: UniswapV3PoolSwapSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := uvss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (uvss *UniswapV3PoolSwapSelect) BoolsX(ctx context.Context) []bool {
	v, err := uvss.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (uvss *UniswapV3PoolSwapSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = uvss.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{uniswapv3poolswap.Label}
	default:
		err = fmt.Errorf("ent: UniswapV3PoolSwapSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (uvss *UniswapV3PoolSwapSelect) BoolX(ctx context.Context) bool {
	v, err := uvss.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (uvss *UniswapV3PoolSwapSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := uvss.sql.Query()
	if err := uvss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
