// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// Position is the predicate function for position builders.
type Position func(*sql.Selector)

// UniswapV3Collect is the predicate function for uniswapv3collect builders.
type UniswapV3Collect func(*sql.Selector)

// UniswapV3DecreaseLiqudity is the predicate function for uniswapv3decreaseliqudity builders.
type UniswapV3DecreaseLiqudity func(*sql.Selector)

// UniswapV3IncreaseLiqudity is the predicate function for uniswapv3increaseliqudity builders.
type UniswapV3IncreaseLiqudity func(*sql.Selector)

// UniswapV3Transfer is the predicate function for uniswapv3transfer builders.
type UniswapV3Transfer func(*sql.Selector)
